drivers/lpc_iocon/fsl_iocon.h, drivers/lpc_iocon_lite/fsl_iocon.h
Some improvements to the lpc_iocon and lpc_icon_lite drivers.
lpc_icon:
- Removed duplicate macro defintions.
- Renamed `IOCON_I2C_SLEW` macro to `IOCON_I2C_MODE` to match its companion `IOCON_GPIO_MODE`. The original is kept as a deprecated symbol.
lpc_icon_lite:
- Fixed the size of the `iocon_group_t::modefunc` struct member. It was 16 bits wide, but the `IOCON_DAC_MODE_EN` flag has a bit shift of 16, meaning it won't fit into the bitfield. In practice it probably worked because the bitfield type is `uint32_t` but only 24 bits were defined. But the behaviour is undefined by the C language.
I can bump the micro versions of the drivers if you like.
=> lpc_iocon driver improvements

drivers/qspi/fsl_qspi.c
More details:
https://community.nxp.com/t5/MCUXpresso-SDK/fsl-qspi-c-init-sequence-not-working-when-u-boot-configures-QSPI/m-p/1077439
=> init sequence not working when u-boot configures QSPI for AHB reads

drivers/sai/fsl_sai_edma.c, drivers/sai/fsl_sai_edma.h
Currently API for SAI EDMA transfers assumes that audio data can only be interleaved (e.g. sent via a single wire I2S0_TXD0) but for example K66/K26 MCUs support output of non-interlieved audio using 2 wires via the I2S0_TXD0 and I2S0_TXD1 pins.
The proposed change allows to send non-interlieved data using SAI EDMA mechanism. In our case this method works successfully for transmitting native DSD non-interlieved data to ESS Technology audio DACs (ES9218P, ES9038Q2M).
**Tests**
- Hardware setting: K66/K26, ES9218P or ES9038Q2M
- Toolchain:
Please …
=> Support for multichannel SAI EDMA transfers

drivers/sai/fsl_sai.c, drivers/sai/fsl_sai.h
This patch fixes FIFO Combine mode which is not activated due to a wrong name of the feature define `FSL_FEATURE_SAI_HAS_FIFO_FUNCTION_COMBINE`. The define, according to the device-specific `feature.h` header, shall be named `FSL_FEATURE_SAI_HAS_FIFO_COMBINE_MODE`: https://github.com/NXPmicro/mcux-sdk/blob/67e6737857daba7bb1b4c0d4ecf69fb0a3afd084/devices/MK66F18/MK66F18_features.h#L793
Scanning the whole SDK for the existence\remainder of `FSL_FEATURE_SAI_HAS_FIFO_FUNCTION_COMBINE` did not reveal anything, so the proposed change is safe to apply.
I have proposed it via the Technical Support already some time ago but it is more relevant to apply the changes via the PR to my view.
**Type of change** (please delete options that are not …
=> Fix FIFO Combine mode not activated due to a wrong device feature definition

utilities/debug_console/debug_console/fsl_debug_console.c, utilities/debug_console/debug_console/fsl_debug_console.h, utilities/debug_console_lite/fsl_debug_console.c, utilities/debug_console_lite/fsl_debug_console.h
to make it possible to wrap SDK's logging into a higher level user-side logging API.
Current SDK's logging API (`DbgConsole_Printf`) is sufficient in case user-side implementation is using only NXP's logging but in reality it is not always true and for better debugging (for example when MCUXpresso IDE can not be used) some additional logging can be required, for example the one offered by Segger's J-Link RTT Viewer (a standalone console logging utility) and its companion API (`SEGGER_RTT_vprintf`).
User would want to wrap logging into a single logging function or logging C++ class but absence of vprintf-like API makes it really troublesome.
This PR adds vprintf functionality to the SDK and makes it possible to wrap SDK's logging API easily …
=> Add DbgConsole_Vprintf/DbgConsole_BlockingVprintf new API

drivers/lpuart/fsl_lpuart_edma.h
I wasted a lot of time chasing around UART issues that could have been prevented if the documentation explained that all interrupts get disabled when the user creates an EDMA handle, and that the `LPUART_TransferEdmaHandleIRQ()` function must be called on transmission complete.
Signed-off-by: Andres O. Vela <andresovela@gmail.com>
=> Improved some docs for LPUART_EDMA driver

drivers/lpuart/fsl_lpuart_edma.c
This PR fixes a potential issue that could happen if the user of the driver enables other UART interrupts.
Signed-off-by: Andres O. Vela <andresovela@gmail.com>
**Tests**
- Toolchain:
=> Fix handling of TX complete interrupt in LPUART EDMA

boards/evkmimxrt1160/xip/driver_xip_board_evkmimxrt1160.cmake
Add xip file for MIMXRT1160 EVK. The driver_xip_board_<board> file is missing
**Tests**
=> Add missing xip cmake file for RT1160

drivers/pmu/driver_pmu.cmake
Adds pmu driver cmake file, in preparation for including this driver
component into Zephyr.
Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>
The pmu driver component does not have a CMake file to allow it to be included. This PR adds a pmu driver CMake file, so this driver can be imported like other drivers are in the  Zephyr NXP hal.
=> Add pmu driver cmake file

boards/evkbimxrt1050/xip/driver_xip_board_evkbimxrt1050_qspi.cmake, boards/evkbimxrt1050/xip/evkbimxrt1050_flexspi_nor_qspi_config.c
Add support for mimxrt1050_evk_qspi. This board should support both boot-from-hyperflash and boot-from-qspi. This modification enables a modified board to boot from the on-board qspi nor chip.
Signed-off-by: Xabier Marquiegui <xmarquiegui@ainguraiiot.com>
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>
New feature (non-breaking change which adds functionality)
=> mcux: Add support for mimxrt1050_evk_qspi

devices/MIMXRT1061/MIMXRT1061.h, devices/MIMXRT1062/MIMXRT1062.h, devices/MIMXRT1064/MIMXRT1064.h
Signed-off-by: Yaoxing Shan <shanyaoxing12@outlook.com>
ENET2 does not work with the original definition because it conflicts with some other driver definitions, such as `fsl_clock.h`:
````c
/*! @brief Clock ip name array for ENET. */
#define ENET_CLOCKS \
{ \
kCLOCK_Enet, kCLOCK_IpInvalid, kCLOCK_Enet2 \
}
````
The driver cannot find the correct clock ip based on the index of the array.
I refer to the definition of FLEXSPI and make reasonable modifications to the definition of ENET. After the modification, ENET2 can work normally.
**Tests**
- Hardware setting: MIMXRT1061CVL5A
- Toolchain: GNU Arm Embedded Toolchain 10.3-2021.10
- …
=> Fix the definition of ENET for i.MX RT1060 family

middleware/usb/include/usb.h
Any inclusion of `usb.h` gives redefinition warnings at compile time.
The `MAKE_VERSION` macro is defined in `fsl_common.h` [here](https://github.com/NXPmicro/mcux-sdk/blob/main/drivers/common/fsl_common.h#L57).
`usb.h` already includes `fsl_common.h` [here](https://github.com/NXPmicro/mcux-sdk/blob/main/middleware/usb/include/usb.h#L14), therefore the redefinition is not necessary.
Bug fix (non-breaking change which fixes an issue)
=> Removed redefinition of `MAKE_VERSION` macro

drivers/flexcan/fsl_flexcan.c
The FLEXCAN driver uses an apparently wrong CAN_Type*/base address as argument to the `s_flexcanIsr` handler for interrupts on FLEXCAN2. This change makes the `CAN_FD2_DriverIRQHandler` use the correct base address.
Use correct base address pointer in `CAN_FD2_DriverIRQHandler` of the flexcan driver.
Fixes #100
**Tests**
- Hardware setting: MIMX8ML8
- Toolchain: arm-none-eabi-gcc 12.2.0
Try to send or receive any CAN frame on FLEXCAN2 using the transactional API
=> Fixes #100. Fix CAN_Type* in FLEXCAN2 ISR

devices/MIMX8ML8/MIMX8ML8_dsp_features.h, devices/MIMX8ML8/all_lib_device_MIMX8ML8_dsp.cmake, devices/MIMX8ML8/device_system_dsp.cmake, devices/MIMX8ML8/fsl_device_registers.h, devices/MIMX8ML8/system_MIMX8ML8_dsp.c, devices/MIMX8ML8/system_MIMX8ML8_dsp.h, drivers/common/driver_common.cmake, drivers/common/fsl_common.h
Link nxp_adsp_imx8m board with MIMX8ML8 device.
In Zephyr, the DSP support for i.MX8MP is the nxp_adsp_imx8m board.
For now, this is needed for enabling UART console, in Zephyr, for the Audio DSP from i.MX8MP.
When other peripherals need to be enabled, this device can be updated.
**Tests**
Tested multiple Zephyr samples (hello_world, synchronization, dining philosophers) - all are working and the output is displayed on the console.
- Hardware setting: i.MX8MP board
- Toolchain: gcc
Build Zephyr samples (hello_world, synchronization, dining …
=> Link nxp_adsp_imx8m board with MIMX8ML8 device

drivers/flexio/fsl_flexio_spi.c
When implementing multiple FLEXIO SPIs, the parent interrupt handler calls all child interrupt handlers in turn, for example FLEXIO_SPI_MasterTransferHandleIRQ().
The problem appears when the interrupt is generated by one interface, and in another interface the send buffer is empty
(kFLEXIO_SPI_TxBufferEmptyFlag is set), and there is no data in the receive buffer yet (kFLEXIO_SPI_RxBufferFullFlag is not set), then without waiting for data in the receive buffer, the handler will send new data, which will result in to data loss (SHIFTBUF Overrun). Since in SPI MASTER mode an interrupt is generated only when the receive buffer is full, the child interrupt handler should only be executed when the receive buffer is full.
Signed-off-by: Mikhail Siomin <mikhail.siomin@nxp.com> …
=> drivers: flexio: fixes SPI Master SHIFTBUF Overrun

drivers/flexcan/fsl_flexcan.c
Propagate timestamp on kStatus_FLEXCAN_RxOverflow status when using the FlexCAN transactional APIs. Originally submitted to the NXP HAL in Zephyr RTOS: https://github.com/zephyrproject-rtos/hal_nxp/pull/217
**Tests**
- Hardware setting: twr_ke18f, mimxrt1024_evk, frdm_k64f
- Toolchain: Zephyr SDK 0.15.2
- Test Tool preparation: N/A
- Any other dependencies: Zephyr RTOS
=> mcux: mcux-sdk: driver: flexcan: propagate timestamp on RxOverflow

devices/MIMX8ML8/all_lib_device_MIMX8ML8_dsp.cmake
Add MU support for HiFi4 DSP from i.MX8 M Plus target.
This is used for IPC.
Having this enabled we can run the openamp_rsc_table sample from Zephyr:  https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/ipc/openamp_rsc_table
Enable MU for DSP
**Tests**
- Hardware setting: DSP from i.MX8MP
- Toolchain: gcc
Build Zephyr sample `openamp_rsc_table` for nxp_adsp_imx8m board
Run Zephyr sample `openamp_rsc_table `and the output will be displayed on console.
=> Enable MU for HiFi4 DSP from i.MX8M Plus

drivers/common/driver_common.cmake
With newer toolchain versions (e.g RI-2023.11) Xtensa uses clang compiler.
Because the binary name for compiler is now xt-clang we fail to correctly identify MCUX_CPU_ARCH because we were looking for 'xtensa' string.
Fix this by also looking for 'xt-clang'.
**Tests**
- Hardware setting: imx8mp
- Toolchain: imx-audio-toolchain/Xtensa_Tool/install/tools/RI-2023.11-linux/XtensaTools/bin/xt-clang
```
Go to SOF directory, setup Xtensa toolchain and run build script:
$ …
```
=> fsl_common: Add support for xt-clang compiler

drivers/pit/fsl_pit.c
Add missing guards to avoid compilation warnings when building PIT driver with clock control driver disabled.
Example of warning without this patch:
```
[136/182] Building C object modules/hal_nxp/hal_nxp/CM...__hal__nxp.dir/mcux/mcux-sdk/drivers/pit/fsl_pit.c.ob 
C:/Users/user/zephyr/modules/hal/nxp/mcux/mcux-sdk/drivers/pit/fsl_pit.c:42:17: warning: 'PIT_GetInstance' defined but not used [-Wunused-function]
42 | static uint32_t PIT_GetInstance(PIT_Type *base)
|
```
**Tests**
- Hardware setting: 
- Toolchain: Zephyr SDK
Please describe the tests that you ran to verify your changes. Provide …
=> drivers: pit: fix compiler warning when clocks disabled

devices/MIMX8ML8/MIMX8ML8_dsp_features.h, devices/MIMX8ML8/drivers/fsl_clock.h
Since the Zephyr IRQSTEER driver doesn't use `IRQSTEER_Init()`/`IRQSTEER_Deinit()` I'm unable to test commit 2ce87ce
=> devices: MIMX8ML8: Add support for new IRQSTEER driver

drivers/ftm/fsl_ftm.c, drivers/ftm/fsl_ftm.h
Add missing guards to avoid compilation warnings when building with clock control driver disabled.
Add missing guards to avoid compilation warnings when building FTM driver with clock control driver disabled.
Example of warning without this patch:
```
Building C object modules/hal_nxp...dir/mcux/mcux-sdk/drivers/ftm/fsl_ftm.c.obj
/home/user/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/ftm/fsl_ftm.c:72:17: warning: 'FTM_GetInstance' defined but not used [-Wunused-function]
72 | static uint32_t FTM_GetInstance(FTM_Type *base)
|
```
**Tests**
- Toolchain: Zephyr SDK …
=> drivers: ftm: fix compiler warning when clocks disabled

devices/MIMX9352/drivers/fsl_edma_soc_rev2.h, drivers/edma_rev2/driver_edma_rev2.cmake, drivers/edma_rev2/fsl_edma_rev2.c, drivers/edma_rev2/fsl_edma_rev2.h
Tested locally using Zephyr+SOF on i.MX93
The point of this new revision is to provide a standard API that will work for any EDMA revision and also allows the usage of virtual addresses. The already existing edma4 driver can't be used because it only allows for identity mapped virtual addresses, which is a bad restriction for an MPU.
For now, this revision works for EDMA3 and EDMA4. I'm going to have to tweak it a little bit if we decide to support more EDMA revisions.
=> drivers: Introduce revision 2 of the edma driver

components/css_pkc/src/comps/mcuxCsslMemory/inc/impl/mcuxCsslMemory_Compare_asm.h, drivers/common/fsl_common_arm.c
This commit fixes labels in inline assembly to use unique identifiers for internal labels.
This fix is required to be able to use LTO.
**Tests**
Detected and fixed here: https://github.com/zephyrproject-rtos/zephyr/pull/66392
=> mcux: mcux-sdk: Fix labels in inline assembly

drivers/lpc_dma/fsl_dma.c, drivers/lpc_dma/fsl_dma.h
The `SET` and `CLR` peripheral registers will set and clear bits in the underlying register without requiring a racy read-modify-write sequence. ABORT is write-only and has essentially the same semantics.
The current code using |= defeats this safety and in a multithreaded environment, this could inadvetently set bits which were recently cleared by another thread.
Replace the use of `DMA_COMMON_REG_GET(...) |= 1 << x` with `DMA_COMMON_REG_SET(..., | 1 << x)` to only write a 1 to the desired bit, leaving all others alone.
Fixes: #173
**Tests**
TBD
- Hardware setting: MIMXRT595 in custom application
- Toolchain: ARM GCC
- Any other …
=> drivers: fsl_dma: Fix incorrect access of common registers

components/audio/fsl_adapter_audio.h, components/audio/fsl_adapter_flexcomm_i2s.c, components/audio/fsl_adapter_sai.c
`s/msaterSlave/masterSlave/g`
To be merged with: https://github.com/nxp-mcuxpresso/mcux-sdk-examples/pull/25
BTW, is this component actively maintained / used / suggested?
=> components: Fix mispelled masterSlave

submanifests/README.txt, submanifests/example.yaml.sample, west.yml
Allow to import additional repositories with submanifests which won't generate merge conflicts in the west.yaml file.
The README.txt and example.yaml.sample were copied from the Zephyr Project.
=> west: Add submanifests

components/log/fsl_component_log.c, components/log/fsl_component_log.h, components/log/fsl_component_log_config.h
Fix LOG_MAX_MESSAGE_LENGTH typo in log component.
Signed-off-by: Javier Santos <jasr93@outlook.es>
Fix LOG_MAX_MESSAGE_LENGTH typo in log component.
**Tests**
- Toolchain:
=> components: log: fix typo

drivers/hashcrypt/fsl_hashcrypt.c, drivers/sha/fsl_sha.c
when building with zephyr, fsl_hashcrypt.c and fsl_sha.c triggers compiler warnings due to the macro BUILD_ASSERT being already defined.
rename the macros to have unique names to avoid this.
- [-] I have added tests that prove my fix is effective or that my feature works.
fixes a compilation warning.
**Tests**
- Toolchain:
note: is this the correct repo for this? i have found https://github.com/nxp-mcuxpresso/mcuxsdk-core but it's unclear which branch to merge to in …
=> fix compiler warning when built with zephyr
