nxp-mcuxpresso/mcux-sdk

components/srtm/include/srtm_defs.h, components/srtm/port/srtm_config.h, components/srtm/port/srtm_mutex_freertos.c, components/srtm/port/srtm_sem_freertos.c, components/srtm/srtm/srtm_dispatcher.c, components/srtm/srtm/srtm_dispatcher_struct.h, components/srtm/srtm/srtm_message_struct.h, components/srtm/srtm/srtm_mutex.h, components/srtm/srtm/srtm_peercore.c, components/srtm/srtm/srtm_peercore_struct.h, components/srtm/srtm/srtm_sem.h
PR related to #10. Couldn't change service file as i didn't find any here.
**Tests**
- Toolchain:
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
- [] Run Test
=> Propose for srtm freertos static api usage

CMSIS/Driver/Include/CMSIS_Driver_Include_Common.cmake, CMSIS/Driver/Include/CMSIS_Driver_Include_I2C.cmake, CMSIS/Driver/Include/CMSIS_Driver_Include_SPI.cmake, CMSIS/Include/CMSIS_Include_common.cmake, CMSIS/Include/CMSIS_Include_core_cm0plus.cmake, CMSIS/Include/CMSIS_Include_core_cm33.cmake, CMSIS/Include/CMSIS_Include_core_cm4.cmake, CMSIS/Include/CMSIS_Include_core_cm7.cmake, CMSIS/Include/CMSIS_Include_dsp.cmake
Signed-off-by: Dane Walton <dane.walton@microsoft.com>
**Tests**
- Toolchain:
=> make cmsis target includes public

devices/MIMXRT595S/device_system.cmake, devices/MIMXRT685S/device_system.cmake
On the MIMXRT685, spilt this out of device_startup.cmake to be consistent with other platforms.
Add device_system.cmake file for MIMXRT595
**Tests**
- Toolchain:
=> Add device_system.cmake file for MIMXRT685 and MIMXRT595

boards/frdmk32l3a6/project_template/board.h, boards/frdmk32l3a6/project_template/cm4/pin_mux.c, boards/frdmk32l3a6/project_template/cm4/pin_mux.h, drivers/sai/fsl_sai.c, drivers/sai/fsl_sai.h, drivers/sai/fsl_sai_edma.c, drivers/sai/fsl_sai_edma.h
Cherry-pick the losing commits after MCUX_2.10.0 update merge back to main.
**Tests**
- Toolchain:
=> Feature/cherry pick overwritten commit after 2.10.0 update

components/exception_handling/cm7/fsl_component_exception_handling.c
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>
replace \n\r with \r\n
**Tests**
- Toolchain:
=> Fix newline character order.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/PULL_REQUEST_TEMPLATE.md
I am always removing line like above in PR as it is garbage. It is important in time of creating issue/pr but not after. So this PR is hidding these comments in final output. Also some markdown parts were fixed.
**Tests**
- Toolchain:
=> Feature/improve GitHub templates

drivers/sema42/fsl_sema42.c
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>
I am just curious if there is a reason why not to use trylock in loop for lock implementation. TryLock and Lock looked to me a bit inconsistent.
**Tests**
- Toolchain:
=> Lock using TryLock

components/codec/tfa9896/fsl_hal_registers.c, components/mem_manager/fsl_component_mem_manager.c, components/mem_manager/fsl_component_mem_manager_light.c, components/panic/fsl_component_panic.c, components/srtm/channels/srtm_rpmsg_endpoint.c
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>
Removing traling spaces may imrprove reading output.
**Tests**
- Toolchain:
=> Removed spaces at/or after the end of line.

devices/MKE16F16/device_CMSIS.cmake
Add missing CMSIS CMake file for the MKE16F16.
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
Add missing file.
**Tests**
- Toolchain:
=> devices: MKE16F16: add missing device_CMSIS.cmake file

components/css_pkc/src/comps/mcuxClHash/src/mcuxClHash.c, components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h
Some small changes in order to solve compilation problems 
=> components: Fix compiler warnings

drivers/semc/fsl_semc.c
Handle the DBICR1[REH2] and DBICR1[REL2] when the register bitfield exist.
Fixes #108
**Tests**
- Hardware setting: RT106x
- Toolchain: IAR
=> MCUXGH-646[SEMC] Fix SEMC_ConfigureDBI bug

devices/MIMX8QM6/MIMX8QM6_ca53_features.h, devices/MIMX8QM6/device_CMSIS.cmake, devices/MIMX8QM6/drivers/fsl_clock.c, devices/MIMX8QM6/drivers/fsl_clock.h, devices/MIMX8QM6/fsl_device_registers.h, devices/MIMX8QM6/system_MIMX8QM6_ca53.c, devices/MIMX8QM6/system_MIMX8QM6_ca53.h
**Tests**
- Toolchain:
This PR is basically a replica of https://github.com/zephyrproject-rtos/hal_nxp/pull/249.
=> Add support for MIMX8QM6's CA53 cores

drivers/lpspi/fsl_lpspi.h
LPSPI in S32K3X4 is affected by errata ERR050456 as described in S32K3X4-0P55A-1P55A-ERRATA document.
The user can reset the transmit FIFO using LPSPIn_CR[RTF] bit and can reset the receive FIFO using LPSPIn_CR[RRF]. However, resetting the FIFO using CR[RTF] and CR[RRF] does not clear the FIFO pointers completely. Workaround this by resetting resetting the entire module using LPSPIn_CR[RST] bit.
NXP have introduced support for S32K3 SoCs to Zephyr RTOS (see https://github.com/zephyrproject-rtos/zephyr/pull/58332) and that port reuse existing Zephyr shim drivers -which are backed by MCUX SDK baremetal drivers- for the hardware blocks that are common between the S32K3 devices and other NXP devices.
LPSPI is one these reused drivers. S32K344 …
=> drivers: lpspi: patch for errata ERR050456

drivers/dma3/fsl_edma.c, drivers/dma3/fsl_edma.h, drivers/dmamux/fsl_dmamux.c
- [ x] I have checked latest main branch and the issue still exists.
- [ x] I did not see it is stated as known-issue in release notes.
- [ x] No similar GitHub issue is related to this change.
- [x ] My code follows the commit guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.
**Tests**
- Toolchain:
=> Dma3 bugfixing

devices/MIMX9352/drivers/fsl_clock.c, devices/MIMX9352/drivers/fsl_clock.h
Replica of https://github.com/zephyrproject-rtos/hal_nxp/pull/247. Tested locally with Zephyr on i.MX93.
=> Add support for newly introduced CCM Rev3 on i.MX93

devices/MIMX8QM6/MIMX8QM6_dsp_features.h, devices/MIMX8QM6/drivers/fsl_clock.c, devices/MIMX8QM6/fsl_device_registers.h, devices/MIMX8QM6/system_MIMX8QM6_dsp.c, devices/MIMX8QM6/system_MIMX8QM6_dsp.h, devices/MIMX8QX6/MIMX8QX6_dsp_features.h, devices/MIMX8QX6/fsl_device_registers.h, devices/MIMX8QX6/scfw_api/main/ipc_imx8qx.c, devices/MIMX8QX6/system_MIMX8QX6_dsp.c, devices/MIMX8QX6/system_MIMX8QX6_dsp.h
Tested with Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/62974
=> Add support for i.MX8QM's and i.MX8QXP's DSP core

devices/MIMX9352/MIMX9352_ca55_features.h, drivers/sai/fsl_sai.c, drivers/sai/fsl_sai.h
Tested locally using SOF with Zephyr on i.MX93.
=> Add necessary changes for supporting the Zephyr DAI SAI driver on i.MX93

components/srtm/channels/srtm_rpmsg_endpoint.c, components/srtm/channels/srtm_rpmsg_endpoint.h
- [] No similar GitHub issue is related to this change.
It is related to this issue https://github.com/nxp-mcuxpresso/mcux-sdk/issues/10. Just another code ported to use static allocation.
**Tests**
- Toolchain:
- [] Build Test
=> Add static support for rpmsg endpoint

drivers/csi/fsl_csi.c, drivers/csi/fsl_csi.h
Currently, the camera framerate is divided by two. This is because the driver only puts the full buffer to the queue and calls the callback at half of the interrupt rate (when there are at least 2 active framebuffers).
On **bare metal**, this issue is not really visible when using more than **2** buffers and the application does not hold the full buffer for too long before submitting it again to the empty buffers queue. But if we use only **2** buffers, the framerate is clearly reduced (by a factor of two).
Especially, when CSI_TransferGetFullBuffer() get called inside the callback function (as in **Zephyr** RTOS), framerate is always reduced by a factor of two **despite of the number of buffers used**.
Rework the driver to fix these issues …
=> drivers: csi: Rework to fix framerate issue

devices/MIMXRT1024/system_MIMXRT1024.c
CMSE is an ARMV8M only feature and therefore cannot be present on the Cortex M7 of the iMXRT1024.
This pull request removes the corresponding lines of code.
**Tests**
Just removed dead code. Therefore no test is necessary
=> CMSE is an ARMV8M only feature and therefore cannot be present on the Cortex M7 of the iMXRT1024.

utilities/debug_console/fsl_debug_console.h
Even thought DEBUGCONSOLE_DISABLE is used the file is declaring function with data types and dependencies which are not needed for this case
**Tests**
- Toolchain:
=> DEBUGCONSOLE_DISABLE is not handled correctly enough
